### ISSUE TITLE
Combat bug

### ISSUE THREAD

**Issue by Nikdoog** [MediaStudy321/ProjectRed#4]
1. Player clicks on fight, starting a battle.
2. Battle plays out at normal speed.
3. Combat zooms through enemies, player hits attack but never attacks

**Comment by ElijahStrauss** [comment]
This was more of a directions problem than an actual bug. The player was suppose to press on a monster after pressing attack. It has now been changed so that the user is directed to press on a monster. DIRECTIONS ARE ALWAYS GOOD!
